### ISSUE TITLE
Clean up transactions older than X days for a given token

### ISSUE THREAD

**Issue by kev-techi** [citizenwallet/indexer#20]
- allow users to set it
- provide a default value
- config per token
- could probably be added to the t_events table

**Comment by xdamman** [comment]
I don't think we want that.

To the contrary, we want this to be the etherscan for the community token. 
Everything should always be there.

**Comment by xdamman** [comment]
This was a good idea back when we wanted to index everything on a single server and USDC was taking all the space. 
Now that we are moving to a more decentralized infrastructure, we don't really need it anymore.

**Comment by kev-techi** [comment]
Yeah, this changes things.

And there can just be a warning for people who want to index very large active contracts that it will consume a lot of data.

Also, that the initial indexing of transactions might take a few hours to complete.
